articles/urls.py
from django.urls import path
from . import views

app_name = 'articles'

urlpatterns = [
    path('', views.index, name = 'index'),
    path('<int:id>/detail', views.detail, name = 'detail'),

    path('create/', views.create, name = 'create'),
    
    path('<int:article_id>/comments/create/',views.comment_create, name = 'comment_create'),
    path('<int:article_id>/comments/<int:id>/delete/', views.comment_delete, name = "comment_delete")
]

board/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('articles/', include('articles.urls')), # articles로 넘겨줌
]

articles/models.py
from django.db import models

# Create your models here.
class Article(models.Model):
    title = models.CharField(max_length=50)
    content = models.TextField()
    # comment_set = 만들어짐(눈엔안보임)

class Comment(models.Model):
    # id =
    content = models.TextField()
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    # article_id =

articles/forms.py
from django import forms
from .models import Article, Comment

class ArticleForm(forms.ModelForm):

    class Meta:
        model = Article
        fields = '__all__'  # 전체 컬럼 다 출력


class CommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        # fields = '__all__'  article 빼야하기 때문에 __all__ (x)

        # fields => 추가할 필드 이름 목록
        # exclude => 제외할 필드 이름 목록
        
        # exclude = ('article', )
        fields = ('content', )

articles/views.py
from django.shortcuts import render, redirect
from .models import Article, Comment
from .forms import ArticleForm, CommentForm

# Create your views here.
def index(request):
    articles = Article.objects.all()

    context = {
        'articles' : articles,
    }   
    return render(request, 'index.html', context)

def create(request):
    if request.method == "POST":
        # 값 넣어주기
        form = ArticleForm(request.POST)

        # 올바른 값으로 들어왔는지(빈값으로 제출 안한경우)
        if form.is_valid():
            form.save()
            return redirect('articles:index')
    else:
        form = ArticleForm()
    
    context = {
        'form': form,
    }
    return render(request, 'form.html', context)

def detail(request, id):
    article = Article.objects.get(id=id)
    comment_form = CommentForm()

    # comment 목록
    # 첫번째 방법
    #comment_list = Comment.objects.filter(article=article)
    
    # 두번째 방법
    # comment_list = article.comment_set.all()

    # 세번째 방법 (제일권장)
    # html코드에서 article.comment_set.all로 사용  # comment_set은 숨어있는 메소드 같은 것
    context = {
        'article' : article,
        'comment_form' : comment_form,
        # 'comment_list' : comment_list,
    }
    return render(request,'detail.html', context)

def comment_create(request,article_id):
    # 사용자가 입력한 정보를 form에 입력
    comment_form = CommentForm(request.POST)

    # 유효성 검사
    if comment_form.is_valid():
        # form을 검사 => 추가로 넣어야 하는 데이터를 넣기 위해 저장 멈춰!
        comment = comment_form.save(commit=False)
    
        # 첫번째방법
        # Article_id를 기준으로 article obj를 가져와서
        # article = Article.objects.get(id=article_id)

        # # article 컬럼에 추가
        # comment.article = article

        # 두번째방법
        comment.article_id = article_id

        # 저장
        comment.save()

        return redirect('articles:detail' , id = article_id)

def comment_delete(request, article_id, id): # article_id: 게시물id / id: 댓글id
    comment = Comment.objects.get(id=id)

    comment.delete()

    return redirect('articles:detail', id=article_id)

articles/templates/detail.html
{% extends 'base.html' %}

{% block body %}

    <h1>{{article.title}}</h1>
    <p>{{article.content}}</p>

    <hr>
    <form action="{% url 'articles:comment_create' article_id=article.id %}" method="POST">
        {% csrf_token %}
        {{comment_form}}
        <input type="submit">
    </form>

    {% if not article.comment_set.all|length %}
        <p>댓글이 없습니다.</p>
    {% endif %}

    {% for comment in article.comment_set.all %}
        <p>{{comment.content}}
            <a href="{% url 'articles:comment_delete' article_id=article.id id=comment.id %}">X</a>
        </p>
    {% endfor %}
{% endblock %}

articles/templates/form.html
{% extends 'base.html' %}

{% block body %}
    <form action="" method="POST">
        {% csrf_token %}
        {{form}}
    <input type="submit">
    </form>    
{% endblock %}

articles/templates/index.html
{% extends 'base.html' %}

{% block body %}
<h1>index</h1>
    {% for article in articles %}
        <p>{{article.title}}</p>
        <a href="{% url 'articles:detail' id=article.id %}">detail</a>
        <hr>
    {% endfor %}
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <a href="{% url 'articles:index' %}">Home</a>
    <a href="{% url 'articles:create' %}">Create</a>
    {% block body %}

    {% endblock %}
</body>
</html>